### ISSUE TITLE
Game Sucks

### ISSUE THREAD

**Issue by alexrsaff** [agforero/TMinesweeper#1]
Game sux. 0/10

**Comment by agforero** [comment]
Hey there, @alexrsaff! I greatly appreciate your thoughtful and meticulously constructed feedback. With all 14 characters you've decided to submit as an issue, I can surely make a huge difference in improving what must be absolutely garbage code. I would like to thank you personally for this wonderful contribution you've made to my code -- nay, dare I say, to the entire world of computer science -- and I sincerely hope that you have an excellent rest of your day.
